### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by WillyWilson1** [CodyHouse/virgo-template#1]
Hi,

I've download, expanded the .zip and put all contents into a directory called virgo.
When  I try the gulp command, I get:

philip-N550JK virgo # sudo npm run gulp watch

> virgo-template@0.0.1 gulp /home/philip/virgo
> gulp "watch"

[11:36:51] Using gulpfile /home/philip/virgo/gulpfile.js
[11:36:51] Starting 'watch'...
[11:36:51] Starting 'browserSync'...
[11:36:51] Starting '<anonymous>'...
[11:36:51] Finished '<anonymous>' after 8.27 ms
[11:36:51] Finished 'browserSync' after 9.2 ms
[11:36:51] Starting 'sass'...
[Browsersync] Access URLs:
 -------------------------------------
       Local: http://localhost:3000
    External: http://192.168.0.10:3000
 -------------------------------------
          UI: http://localhost:3001
 UI External: http://localhost:3001
 -------------------------------------
[Browsersync] Serving files from: main
[Browsersync] 1 file changed (style.css)
[11:36:52] gulp-postcss: style-fallback.css
postcss-css-variables: /home/philip/virgo/main/assets/css/style-fallback.css:1:58650: variable --color-shadow is undefined and used without a fallback
postcss-css-variables: /home/philip/virgo/main/assets/css/style-fallback.css:1:59589: variable --color-shadow is undefined and used without a fallback
postcss-css-variables: /home/philip/virgo/main/assets/css/style-fallback.css:1:60588: variable --color-shadow is undefined and used without a fallback
postcss-css-variables: /home/philip/virgo/main/assets/css/style-fallback.css:1:61587: variable --color-shadow is undefined and used without a fallback
postcss-css-variables: /home/philip/virgo/main/assets/css/style-fallback.css:1:61930: variable --color-shadow is undefined and used without a fallback
postcss-css-variables: /home/philip/virgo/main/assets/css/style-fallback.css:1:68239: variable --color-shadow is undefined and used without a fallback
postcss-css-variables: /home/philip/virgo/main/assets/css/style-fallback.css:1:93742: variable --color-shadow is undefined and used without a fallback
[11:36:52] Finished 'sass' after 776 ms
[11:36:52] Starting 'scripts'...
[Browsersync] 1 file changed (scripts.js)
[Browsersync] 1 file changed (scripts.min.js)
[11:36:52] Finished 'scripts' after 175 ms
[11:36:52] Starting '<anonymous>'...
[Browsersync] Reloading Browsers... (buffered 2 events)
[Browsersync] Couldn't open browser (if you are using BrowserSync in a headless environment, you might want to set the open option to false)

When using npm install, I got:

Binary found at /home/philip/virgo/node_modules/node-sass/vendor/linux-x64-67/binding.node
Testing binary
Binary is fine
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN virgo-template@0.0.1 No repository field.
npm WARN virgo-template@0.0.1 license should be a valid SPDX license expression
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 615 packages from 451 contributors and audited 10756 packages in 18.769s
found 0 vulnerabilities

Any ideas? I'm using Linux Mint 18.3

Regards,

PB

**Comment by claudia-romano** [comment]
Hi there, sorry about this issue.
The message you get about the --color-shadow variable is a warning message that the postcss-css-variable plugin (that we use in the gulp config file) incorrectly throws. 

As this is a warning, it does not affect your workflow (we are working on a solution for that!). 

About the browser window not getting opened, if you run the gulp command and then go to:
http://localhost:3000

do you see your project? Does it refresh if you make changes to the css/js files? Thank you.

**Comment by WillyWilson1** [comment]
Hi,

Thanks for clarification.

I ran the gulp command again, and indeed, the pages load in the browser (FF) and can be used. Looks very nice.
However, making changes - I just tried with the html - does not result in changes in the browser, even thought the browser sends the message 'BrowserSync: connected'. This is the case even if I reload the file.

Regards,

PB

**Comment by WillyWilson1** [comment]
Hi,

Sorry, I seem to have closed this by mistake.

PB

**Comment by WillyWilson1** [comment]
Hi,

It is now working - I was looking in the wrong place for changes. Sorry.

PB
